name: Release

on:
  push:
    branches: ["**"]
    tags:
      - 'v*.*.*'
    
permissions:
  contents: write

jobs:
  test-db:
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            artifact_name: lmah-inventory-rs
            asset_name: lmah-inventory-rs-linux-x86_64

    runs-on: ${{ matrix.os }}
    env:
      DATABASE_URL: "sqlite://todelete.db"
    steps:
    - uses: actions/checkout@v6
    - uses: cachix/install-nix-action@v31
    - uses: cachix/cachix-action@v17
      with:
        name: devenv
    - name: Install devenv.sh
      run: nix profile add nixpkgs#devenv

    - name: Install the sqlx-cli
      run: devenv shell cargo install sqlx-cli --no-default-features --features sqlite

    - name: Create the database
      run: devenv shell sqlx database create

    - name: Apply the migrations
      run: devenv shell sqlx migrate run

  build:
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            artifact_name: lmah-inventory-rs
            asset_name: lmah-inventory-rs-linux-x86_64

    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v6
    - uses: cachix/install-nix-action@v31
    - uses: cachix/cachix-action@v17
      with:
        name: devenv
    - name: Install devenv.sh
      run: nix profile add nixpkgs#devenv

    - name: Run a single command in the devenv shell
      run: devenv shell cargo build --release

    - name: Upload artifact
      if: startsWith(github.ref, 'refs/tags/v')
      uses: actions/upload-artifact@v4
      with:
        name: ${{ matrix.asset_name }}
        path: target/${{ matrix.target }}/release/${{ matrix.artifact_name }}

  release:
    name: Create Release
    needs: build
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          draft: false
          prerelease: false
          generate_release_notes: true
          files: artifacts/**/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
